// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izcesgdrzkduvgcukxwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Y2VzZ2RyemtkdXZnY3VreHdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDQ4ODIsImV4cCI6MjA3MTY4MDg4Mn0.iKKEf0Gif6aOcApgiLI0VXVF18Utm3qk-T66wyoz4aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});